using Xamarin.Forms; using BCP.Common.Models; using System.Collections.Generic; using BCP.Forms.Views;

namespace BCP.Forms.Controls {     public class UsefultoolStackLayout : StackLayout     {         public List<Resource> UsefulTools         {             get { return (List<Resource>)GetValue(UsefulToolsProperty); }             set { SetValue(UsefulToolsProperty, value); }         }          public static readonly BindableProperty UsefulToolsProperty = BindableProperty.Create(nameof(UsefulTools),                                                                                               typeof(List<Resource>),                                                                                               typeof(UsefultoolStackLayout),                                                                                               null, BindingMode.TwoWay, null, propertyChanged: (bindable, oldValue, newValue) =>                                                                                               {
                                                                                                  if (newValue != null)
                                                                                                  {
                                                                                                      var resources = newValue as List<Resource>;
                                                                                                      if (resources != null)
                                                                                                      {
                                                                                                          var thisView = ((UsefultoolStackLayout)bindable);
                                                                                                          thisView.Children.Clear();                                                                                                           foreach (var res in resources)                                                                                                           {
                                                                                                              thisView.Children.Add(new UseFullToolsView()                                                                                                               {                                                                                                                   BindingContext = res                                                                                                               });                                                                                                           }
                                                                                                      }
                                                                                                  }

                                                                                              });          public UsefultoolStackLayout()         {             this.Orientation = StackOrientation.Vertical;         }     } }   